import discord
import os
from discord.ext import commands


def run_commands(client):
  #client = commands.Bot(command_prefix="!")

  @client.command()
  async def command1(ctx, arg):
    await ctx.send(arg)

  #client.run(os.environ['token']) #token is generated by discord
