import os #hides token
import discord
import requests #get data from APIs
import json
import random
#from commands import run_commands
from zenquote import get_quote
from keep_alive import keep_alive
from discord.ext import commands
#https://discord.com/oauth2/authorize?client_id=851180231800520734&permissions=2148005952&scope=bot


bot = commands.Bot(command_prefix="!", case_insensitive = True)
#word_monitor = ["Conan"]

#word_responses = ["Detective Conan is not even a good show kappa"]

@bot.event
async def on_ready():
  #set status of client
  await bot.change_presence(status=discord.Status.online, activity=discord.Game('with your heart'))
  print('Logged in as')
  print(bot.user.name)
  print(bot.user.id)
  print('------')


'''
@client.event  
async def on_message(message):

  
  if message.author == client: #does nothing if the message is from the bot/client
    return
  
  

  msg = message.content.lower() #sets message to lowercase

  #responds with Hello! if someone types $hello
  if msg.startswith('!hello'):
    await message.channel.send('안녕하세요!')
  
  if msg.startswith('!inspire'):
    quote = get_quote()
    await message.channel.send(quote)

  if msg.startswith('!kumiko'):
    await message.channel.send('https://imgur.com/FPjjOuh')
  #if any(word in msg for word in word_monitor):
  #  await message.channel.send(random.choice(word_responses))
  await client.process_commands(message)
'''
@bot.command()
async def hello(ctx):
    await ctx.send('안녕하세요!')

@bot.command()
async def inspire(ctx):
  quote = get_quote() 
  await ctx.send(quote)

@bot.command()
async def commands(ctx):
  embedret = discord.Embed(title="IU - List of Commands", description="prefix: !", color = 0xcc99cc)
  embedret.add_field(name="!hello", value="IU says hello back", inline=False)
  embedret.add_field(name="!inspire", value="IU inspires you", inline=False)
  embedret.add_field(name="!flipcoin", value="IU flips a coin", inline=False)
  await ctx.send(embed=embedret)

@bot.command()
async def play(ctx, arg):
  if arg == "palette":
    await ctx.send("https://www.youtube.com/watch?v=d9IxdwEFk1c")

@bot.command()
async def flipcoin(ctx):
  if random.randint(1, 2) == 1:
    await ctx.send("Heads, born to be a gambler!")
  else:
    await ctx.send("Tails, it's a no kids zone!")

@bot.command()
async def kumiko(ctx):
  await ctx.send('https://imgur.com/FPjjOuh')


keep_alive()
#runs the bot
bot.run(os.environ['token']) #token is generated by discord

